[phases.setup]
nixPkgs = ["python312", "pip", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn server:app --host 0.0.0.0 --port ${PORT}"
